# Generated by Django 3.0 on 2021-05-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_carcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('is_status', models.IntegerField(default=1)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.CarCategory')),
            ],
        ),
    ]
