# Generated by Django 3.0 on 2021-05-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('is_status', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null='True')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
