# Generated by Django 3.0 on 2021-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rolerqst'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(choices=[('product quality issues', 'product quality issues'), ('I want to change address/phone number', 'I want to change address/phone number'), ('I have purchased product somewhere else', 'I have purchased product somewhere else'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
