# Generated by Django 3.0 on 2021-05-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_myorders_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(choices=[("I don't want this service_type", "I don't want this service_type"), ('I want to change address/phone number', 'I want to change address/phone number'), ('High cost of service', 'High cost of service'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
