# Generated by Django 3.0 on 2021-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210522_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Expyear',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='creditcardnumber',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='expmonth',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='nameoncard',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
    ]
