# Generated by Django 3.0 on 2021-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20210603_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
    ]
