# Generated by Django 3.0 on 2021-06-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=40, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null='True'),
        ),
    ]
