# Generated by Django 3.0 on 2021-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
