# Generated by Django 3.0 on 2021-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_myorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('carcategory', models.CharField(choices=[('Audi', 'Audi'), ('Toyota', 'Toyota'), ('Shift', 'Shift'), ('pollo', 'pollo')], max_length=20)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='myorders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserService',
        ),
    ]
